### PR TITLE
chore: ESLintとprettierの設定

### LINKED ISSUE #31: コードルールとフォーマッターの設定
**Is your feature request related to a problem? Please describe.**
コードを編集する環境によっていろいろなコード書き方ができてしまう。
フォーマットをそれぞれだったりしてコードが汚くなって可読性が下がってしまう。

**Describe the solution you'd like**
ESLintによってコードのルールを決定し、フォーマットをprettierによって揃える

**Additional context**

- https://zenn.dev/resistance_gowy/articles/91b4f62b9f48ec#(1)next.js%E3%82%92%E3%82%A4%E3%83%B3%E3%82%B9%E3%83%88%E3%83%BC%E3%83%AB
- https://nextjs.org/docs/pages/building-your-application/configuring/eslint#recommended-plugin-ruleset

### PR DESCRIPTION
**Pull request by kokiito**
## Why
ESLintとしてlinterを設定しておくと、コードが汚くにくい。
コード書くたびにチェックするようにできるので複数人の開発に使えるため
また、prettierを設定しておくとコードが綺麗になる。vscode用の設定も追加するとlocalで編集されてもフォーマットを統一できる。

## What
- ESLintの設定
- prettierの設定

## 参考リンク
https://blog.monorevo.jp/post-2104

### CODE REVIEW

**Comment by psmuler** [comment]
Great.
Can we ignore the  `@typescript-eslint/no-unused-vars` rule for now and format later (as the app header is the main source of violation and we would refactor them in a while), or we should not overlook them?

**Comment by kokiito** [comment]
@psmuler 
Either method is no problem. It depends on which you prefer.
I recommend the way you remove unused code from now because you can  read and write code easily.
You can edit this request freely.

**Comment by kokiito** [comment]
@psmuler  
Because I cannot guarantee that it will work, this request doesn't need merge or merge with adding `@typescript-eslint/no-unused-vars` rule

**Comment by kokiito** [comment]
> **The latest updates on your projects**. Learn more about [Vercel for Git ↗︎](https://vercel.link/github-learn-more)
> 
> Name	Status	Preview	Comments	Updated (UTC)
> **react-yjs**	❌ Failed ([Inspect](https://vercel.com/mulers-projects/react-yjs/3ZnegpBM9PVcsG4Lh9PEqi34JpSk))			Dec 24, 2023 4:01am

@psmuler  By the way, did you confirm this error?
probably, it doesn't deploy to Vercel now.
I don't know the error because of the lack of my authority to check your Vercel project console.

**Comment by psmuler** [comment]
Removed all the unused import and added the rule `no-unused-var:off`

The error remaining is:
`Error: Require statement not part of import statement.  @typescript-eslint/no-var-requires`
You can get rid of it by installing latest [y-websocket library](https://github.com/yjs/y-websocket/tree/master) v1.5.1

**Pull request merged**
